# Production Profile Configuration
# This configuration is designed for production environments with security best practices
# All sensitive values MUST be provided via environment variables

spring:
  application:
    name: motel-booking-system

  # Database Configuration
  # REQUIRED: DATABASE_URL, DATABASE_USERNAME, DATABASE_PASSWORD must be set
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/motel_booking}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    # HikariCP Connection Pool Configuration
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:20}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
      connection-timeout: ${DB_POOL_TIMEOUT:30000}
      idle-timeout: ${DB_POOL_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_POOL_MAX_LIFETIME:1800000}
      pool-name: MotelBookingPool
      auto-commit: false
      leak-detection-threshold: ${DB_LEAK_DETECTION:60000}
      connection-test-query: SELECT 1
      validation-timeout: ${DB_VALIDATION_TIMEOUT:5000}

  # Redis Cache Configuration
  # REQUIRED: REDIS_PASSWORD must be set
  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:true}
      timeout: ${REDIS_TIMEOUT:2000ms}
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:2000ms}
      client-type: ${REDIS_CLIENT_TYPE:lettuce}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:8}
          max-idle: ${REDIS_POOL_MAX_IDLE:8}
          min-idle: ${REDIS_POOL_MIN_IDLE:2}
          max-wait: ${REDIS_POOL_MAX_WAIT:2000ms}

  # JPA/Hibernate Configuration
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
        connection:
          provider_disables_autocommit: true

  # Flyway Database Migration
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
    encoding: UTF-8
    out-of-order: false

  # Email Configuration
  # REQUIRED: MAIL_USERNAME, MAIL_PASSWORD must be set
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# JWT Configuration
# REQUIRED: JWT_SECRET must be set (minimum 256-bit Base64 encoded secret)
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# Logging Configuration
logging:
  level:
    root: INFO
    com.westbethel.motel_booking: INFO
    org.springframework: WARN
    org.springframework.security: INFO
    org.hibernate: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: ${LOG_FILE_PATH:/var/log/motel-booking/application.log}
    max-size: ${LOG_MAX_SIZE:50MB}
    max-history: ${LOG_MAX_HISTORY:90}
    total-size-cap: ${LOG_TOTAL_SIZE:5GB}

# Actuator/Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: production
    export:
      prometheus:
        enabled: true

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  shutdown: graceful

  # Error handling - secure for production
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: false

  # Performance optimizations
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml

  http2:
    enabled: true

  # Connection timeout settings
  tomcat:
    connection-timeout: ${TOMCAT_CONNECTION_TIMEOUT:20000}
    threads:
      max: ${TOMCAT_MAX_THREADS:200}
      min-spare: ${TOMCAT_MIN_SPARE_THREADS:10}
    max-connections: ${TOMCAT_MAX_CONNECTIONS:10000}
    accept-count: ${TOMCAT_ACCEPT_COUNT:100}

# Spring Boot defaults
spring.lifecycle.timeout-per-shutdown-phase: 30s
