global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codespaces-motel-booking'
    environment: 'development'

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'west-bethel-motel-booking'
          instance: 'codespaces'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "alert_rules.yml"
